---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kbs-rolebinding
  labels:
    {{- include "coco-kbs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kbs-role
subjects:
- kind: ServiceAccount
  name: kbs-sa
  namespace: {{ .Release.Namespace }}
