---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kbs-role
  labels:
    {{- include "coco-kbs.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - get
  - watch
